### ISSUE TITLE
Error connecting to GE OPAL01GEPKT

### ISSUE THREAD

**Issue by diggernet** [jdeath/Opal_NuggetIce_ble#1]
So I tried this with the GE model, to see how it would go.  I get this error in the HA log once at startup:

 Error connecting to and getting data from D8:28:C9:XX:XX:XX: D8:28:C9:XX:XX:XX - D8:28:C9:XX:XX:XX: Failed to connect after 4 attempt(s): failed to discover services, device disconnected 

The MAC address is correct for this machine, so at least that much is working.  Unfortunately I am not familiar enough with either BLE or HA integrations to do much debugging.  Is there some way to trigger this to try again, short of restarting HA each time?  Can you give some guidance on how to modify your code to learn why it fails?

Thanks!

**Comment by jdeath** [comment]
First make sure, nothing else is connected to the icemaker. Remove it from any android/ios apps. Make sure you did not run it with the ESPhome code. 

You can reload the integration from the integrations tab GUI, but if you change any code you must restart homeassistant.

if your turn on debugging, you may get more output. In your configuration.yaml do and restart homeassistant:

```logger:
  default: error
  logs:
    custom_components.opal_ble: debug
```

Maybe that will put more info in the logs. After that, you can put more debugging statements in the config_flow.py file, in the async def async_step_user function.

If they changed the BT protocol, then someone else will have to figure it out...

**Comment by diggernet** [comment]
Ok, nothing else paired to it.  I can't reload from integrations tab because it doesn't appear there.  This error appears to be preventing its discovery as a device, so the integration has never been added.

Had a little trouble with configuration.yaml, until I did some searching and figured out you meant this:
```
logger:
  default: error
  logs:
    custom_components.opal_ble: debug
```

After that I added some debug logs and determined that it is failing in the call to bleak_retry_connector.establish_connection() in update_device() in opal_ble/parser.py.  It never enters _async_step_user.  Unfortunately I know nothing about Bleak, so it gets hard from here.

I noticed this line in update_device():
`device.name = ble_device.address`
That strikes me as a little odd.  Shouldn't it be using ble_device.name?
Not that it matters for my problem, because it never gets that far.

Similarly, the call to establish_connection() is:
`client = await establish_connection(BleakClient, ble_device, ble_device.address)`
Looking at the code for establish_connection(), I noticed that the 3rd argument is called "name".  Just in case it mattered, I used ble_device.name for the 3rd argument.  Still doesn't work, but at least the error message makes more sense:

`2024-01-21 16:15:15.630 ERROR (MainThread) [custom_components.opal_ble.config_flow] Error connecting to and getting data from D8:28:C9:XX:XX:XX: OPAL Bluetooth-XXXXXX - D8:28:C9:XX:XX:XX: Failed to connect after 4 attempt(s): failed to discover services, device disconnected`

So there's a minor suggestion for improvement.
Any ideas about troubleshooting Bleak?

**Comment by jdeath** [comment]
The code is correct and working. Device names are assigned the address. Plugged mine in for first time in months and still works on latest homeassistant. Make sure no phones that have ever been paired with it are on, make sure you do not have ESPHome ble_client: trying to connect to it. Make sure your proxy is up to date and near the unit. There is not much you can do to diagnose a connection issue.

**Comment by diggernet** [comment]
Oh, sorry, I didn't mean to suggest that the code was broken.  Just observing that the Bleak error message makes more sense when it's given the device name instead of address, so the message isn't repeating the address three times.  That is obviously not related to my problem in any way.

I've got no phones paired with the Opal (I didn't even know it had BLE until this weekend when I opened it for cleaning and found myself staring at an unexpected bluetooth module.)  I don't have any ESPHome devices.  And I'm not sure what you are saying about a proxy - I'm just trying to connect to the unit directly from HA Yellow.

Anyway, looks like the next step of this is to read up on BLE to see if I can figure out where/why the connect is failing.
Thanks.

**Comment by jdeath** [comment]
Make sure it is close (2-3 meters) to the HA yellow. I am not sure what else can be diagnosed as the connection simply fails.  They might have disabled the BLE on that model, but I doubt it. You could also try to use the app to connect to it once, then be sure to unpair it or remove the app. Some BLE devices need to be connected to an app once to be properly setup.

Many people use ESP32 configured as BT proxy `https://esphome.io/components/bluetooth_proxy.html`. That allows you to put them around your house and pickup BLE devices more easily.

**Comment by diggernet** [comment]
So many fun dead-ends I've run into...  I've got an old junker phone that is able to pair/unpair the Opal.  I installed the Opal app on it, but Android requires location permissions in order to use bluetooth and the app just kept asking for location permission over and over, even though I'd already given it, so it'd never get far enough to try to connect with the app.  My current phone can pair/unpair the Opal, but apparently the Opal app has been abandoned, because it is not available for the new phone.  My laptop it turns out doesn't support BLE, so it can't even see the Opal.  All I could do was ssh into HA and try to poke at it with bluetoothctl there.  I could see the Opal and get info about it, but couldn't pair with it.  And HA wouldn't see it.

Eventually I ordered a new bluetooth adapter I could use to play with bluetoothctl on my laptop.  After some experimenting, I was finally able to pair, connect, and list attributes that way.  So I went back to HA with ssh and tried there again.  After some sequence of bluetoothctl commands including 'info', 'pair', 'connect', and maybe others, it suddenly connected and HA notified and set up the new device.  Progress!

From what I've seen so far, it seems like maybe something about the hardware or software setup of Home Assistant Yellow makes it unable to automatically detect this Opal model, and you need to manually pair it (which can take multiple attempts) before it's detected.

Now it's connected to the Opal and can read data from it.  No buttons of course.  But it only seems to update the data every 5 minutes or so.  Is that configurable somewhere?

Maybe one of these days I'll try playing with ESPHome...

Thanks!

**Comment by jdeath** [comment]
Weird. So it must require being sent commands first to prime it. If you write down what you did, please post it here so I can put a note for others. The code does do a pair command (That was the secret to get it recognized at all.), so I am not sure why you need to go in manually.

In the const.py file, there is DEFAULT_SCAN_INTERVAL = 600 . change that to whatever you want to speed it up. I would not go too fast, maybe 60 is ok. You will need to restart homeassistant for it to register.

esphome will work with buttons, give it a try. I tried adding buttons to the native integration, but could not get it to work, but it should be possible. 

the yellow is just a raspberry PI. there have been reports of a buggy bluetooth adapter/stack. See this issue: https://github.com/home-assistant/core/issues/90307  

You could also plug the new adapter you got into the yellow (use a USB extender), and see if works better.

**Comment by diggernet** [comment]
Sadly, I do not know for sure what finally got it working.  But it's been working fine ever since.  Well, except for that one time that I noticed it was reporting make state 16.  But that was probably the integration correctly reporting what it was told, because I found the machine had gone into some strange state and locked up and wouldn't even turn off.

Another interesting tidbit is that while exploring it's BLE API further with bluetoothctl, I discovered that all the values this integration uses also support enabling notification.  No idea what it takes to set that up in the integration, but maybe it means polling wouldn't be necessary.

**Comment by jdeath** [comment]
Glad it works. I am not a BLE expert, but I think notifications is a misnomer. You write a command, then start a notify listener to wait for the response to be pushed. If you do not "poll" by writing the command, it does not send anything. This is how the code currently works. look in the parser.py
